name: Validate HTML
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install lychee link checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress .
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}